package com.isec.platform.modules.certificates.service.ingestion;

import com.isec.platform.modules.certificates.dto.ExtractedCertificateMetadata;
import jakarta.mail.Address;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.io.IOException;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.when;

class SanlamEmailParserTest {

    private SanlamEmailParser parser;
    private MimeMessage mockMessage;

    @BeforeEach
    void setUp() {
        parser = new SanlamEmailParser();
        mockMessage = Mockito.mock(MimeMessage.class);
    }

    @Test
    void canParse_ShouldReturnTrueForSanlamSender() throws MessagingException {
        when(mockMessage.getFrom()).thenReturn(new Address[]{new InternetAddress("certificates@dmvic.com")});
        assertTrue(parser.canParse(mockMessage));
    }

    @Test
    void canParse_ShouldReturnFalseForOtherSender() throws MessagingException {
        when(mockMessage.getFrom()).thenReturn(new Address[]{new InternetAddress("info@other.com")});
        assertFalse(parser.canParse(mockMessage));
    }

    @Test
    void parse_ShouldExtractCorrectMetadataWithHtml() throws MessagingException, IOException {
        String body = "<html><body>" +
                "Hello TEST CERTERROR,<br/><br/>" +
                "This e-mail is to inform that your Motor Vehicle Insurance certificate C33981153 is generated by Sanlam Allianz General Insurance (Kenya) Limited. Below are the details of the new Motor Vehicle Insurance certificate.<br/><br/>" +
                "<b>Certificate # :</b> C33981153<br/>" +
                "<b>Policy # :</b> P/101/S1002/2026/01059/0098<br/>" +
                "<b>Vehicle Registration # :</b> TST7722<br/>" +
                "<b>Chassis # :</b> 345435SR<br/>" +
                "<b>Certificate Validity Duration :</b> 31/07/2026 00:00 to 30/08/2026<br/>" +
                "<b>Sum Insured :</b> 2000000<br/>" +
                "</body></html>";

        when(mockMessage.isMimeType("text/html")).thenReturn(true);
        when(mockMessage.getContent()).thenReturn(body);

        ExtractedCertificateMetadata metadata = parser.parse(mockMessage);

        assertNotNull(metadata);
        assertEquals("SANLAM", metadata.getPartnerCode());
        assertEquals("C33981153", metadata.getCertificateNumber());
        assertEquals("P/101/S1002/2026/01059/0098", metadata.getPolicyNumber());
        assertEquals("TST7722", metadata.getRegistrationNumber());
        assertEquals("345435SR", metadata.getChassisNumber());
    }
}
